repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        files: '^(?!CHANGELOG.md|mlflow/pypi_package_index.json|docs/|mlflow/server/js/).+\.(js|md|json|ya?ml)$'
        args: ["--no-config", "--print-width", "100"]
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: python dev/ruff.py
        language: system
        types_or: [python, jupyter]
        stages: [commit]

      - id: black
        name: black
        entry: python dev/black.py
        language: system
        types_or: [python, jupyter]
        stages: [commit]

      - id: blacken-docs
        name: blacken-docs
        entry: blacken-docs
        language: system
        types_or: [python, rst, markdown]
        stages: [commit]

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--rcfile=pylintrc"]
        stages: [commit]

      - id: disallow-rule-ids
        name: disallow-rule-ids
        entry: python ./dev/disallow_rule_ids.py
        language: system
        types: [python]
        stages: [commit]

      - id: rstcheck
        name: rstcheck
        entry: rstcheck
        language: system
        files: README.rst
        stages: [commit]

      - id: must-have-signoff
        name: must-have-signoff
        entry: 'grep "Signed-off-by:"'
        language: system
        stages: [prepare-commit-msg]

      - id: mlflow-typo
        name: mlflow-typo
        entry: dev/mlflow-typo.sh
        language: system
