routes:
  - name: completions
    route_type: llm/v1/completions
    model:
      provider: palm
      name: text-bison-001
      config:
        palm_api_key: $PALM_API_KEY

  - name: embeddings
    route_type: llm/v1/embeddings
    model:
      provider: palm
      name: embedding-gecko-001
      config:
        palm_api_key: $PALM_API_KEY

  - name: chat
    route_type: llm/v1/chat
    model:
      provider: palm
      name: chat-bison-001
      config:
        palm_api_key: $PALM_API_KEY
